const itemArray = [{
    id: 1,
    type: `weapon`,
    element: `debug`,
    levelReq: `1`,
    baseDmg: `500`,
    baseDef: 0,
    itemName: `Debug Axe`,
}, {
    id: 2,
    type: `gear`,
    element: `debug`,
    levelReq: `1`,
    baseDmg: 0,
    baseDef: `500`,
    itemName: `Debug Armor`,
}, {
    id: 3,
    type: `skill`,
    element: `debug`,
    levelReq: `1`,
    baseDmg: `500`,
    baseDef: 0,
    itemName: `Debug Skill`,
}]